# Generated by Django 3.2.4 on 2021-06-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
                INSERT INTO recommend_category
                (category_name, created_at, function1, function2, function3) VALUES
                ('분류 없음', CURRENT_TIMESTAMP, null, null, null),
                ('노트북', CURRENT_TIMESTAMP, '성능', '무게', '발열'),
                ('태블릿', CURRENT_TIMESTAMP, '성능', '액정', '가격'),
                ('키보드/마우스', CURRENT_TIMESTAMP, '디자인', '가성비', '사용감')
            """
        )
    ]
