# Generated by Django 3.2.4 on 2021-08-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]
    operations = [
        migrations.RunSQL([
            """
            INSERT INTO recommend_category
                (category_name, created_at, function1, function2, function3) VALUES
                ('분류 없음', CURRENT_TIMESTAMP, null, null, null),
                ('노트북', CURRENT_TIMESTAMP, '성능', '발열', '무게'),
                ('키보드', CURRENT_TIMESTAMP, '키감', '소음', '가격대비'),
                ('마우스', CURRENT_TIMESTAMP, '사용감', '소음', '가격대비');
            """,
            """
            INSERT INTO recommend_option
                (title, category, tag_id, created_at) VALUES
                ('문서작업/코딩', '키보드', '멤브레인', CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '펜타그래프', CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '기계식 적축', CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '기계식 갈축', CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '텐키', CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '키압 낮음', CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '키압 중간', CURRENT_TIMESTAMP);
            """
        ])]
