# Generated by Django 3.2.4 on 2021-06-14 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
                INSERT INTO recommend_category
                (category_name, created_at) VALUES
                ('분류 없음', CURRENT_TIMESTAMP ),
                ('노트북', CURRENT_TIMESTAMP),
                ('태블릿', CURRENT_TIMESTAMP),
                ('키보드/마우스', CURRENT_TIMESTAMP)
            """
        )
    ]
