# Generated by Django 3.1.7 on 2021-06-25 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_auto_20210625_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-prod_is_thumbnail', 'img_no']},
        ),
    ]
