# Generated by Django 3.2.4 on 2021-08-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_auto_20210830_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='classification',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='option',
            name='flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
