# Generated by Django 3.2.4 on 2021-06-21 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_auto_20210621_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='func1_rate',
            field=models.CharField(choices=[('g', 'Good'), ('s', 'So so'), ('b', 'Bad')], default='s', max_length=1, verbose_name='function1 rate'),
        ),
        migrations.AddField(
            model_name='review',
            name='func2_rate',
            field=models.CharField(choices=[('g', 'Good'), ('s', 'So so'), ('b', 'Bad')], default='s', max_length=1, verbose_name='function2 rate'),
        ),
        migrations.AddField(
            model_name='review',
            name='func3_rate',
            field=models.CharField(choices=[('g', 'Good'), ('s', 'So so'), ('b', 'Bad')], default='s', max_length=1, verbose_name='function3 rate'),
        ),
    ]
