# Generated by Django 3.2.4 on 2021-06-14 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommend', '0003_auto_20210615_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_created_at', models.DateTimeField(auto_now_add=True)),
                ('fav_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.product')),
                ('fav_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fav_created_at'],
            },
        ),
    ]
