# Generated by Django 3.2.4 on 2021-08-23 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_auto_20210625_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_preference',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
