# Generated by Django 3.2.4 on 2021-06-21 11:44

from django.db import migrations, models
import recommend.utils


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_auto_20210621_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_path',
            field=models.ImageField(upload_to=recommend.utils.user_directory_path),
        ),
    ]
