# Generated by Django 3.2.4 on 2021-08-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_auto_20210830_2003'),
    ]

    operations = [
        migrations.RunSQL(
            """
            INSERT INTO recommend_option
                (title, category, classification, tag_id, flag, created_at) VALUES
                ('문서작업/코딩', '키보드', '종류', 13, True , CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '종류', 14, True, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '종류', 15, True, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '종류', 16, False, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '종류', 17, True, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '종류', 18, False, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '종류', 19, False, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '종류', 20, False, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '텐키', 21, True, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '텐키', 22, False, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '방수', 23, False, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '기타', 24, False, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '키압', 25, True, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '키압', 26, True, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '키압', 27, False, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '기타', 28, False, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '기타', 29, False, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '기타', 30, False, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '기타', 31, False, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '기타', 32, False, CURRENT_TIMESTAMP),
                ('문서작업/코딩', '키보드', '기타', 33, False, CURRENT_TIMESTAMP);
            """
        )
    ]
