# Generated by Django 3.2.4 on 2021-06-20 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210614_1849'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommend', '0004_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_no', models.AutoField(primary_key=True, serialize=False)),
                ('review_title', models.CharField(max_length=50, null=True)),
                ('review_text', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prod_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recommend.product')),
                ('user_no', models.ForeignKey(default='유저 정보 없음', on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.review')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_file_path', models.CharField(max_length=200)),
                ('review_is_thumbnail', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.review')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
