# Generated by Django 3.2.4 on 2021-09-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_auto_20210830_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['prod_category_id', 'prod_no']},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['prod_no', '-prod_is_thumbnail', 'img_no']},
        ),
        migrations.AddField(
            model_name='option',
            name='description',
            field=models.CharField(default='', max_length=5),
        ),
    ]
