# Generated by Django 3.2.4 on 2021-09-03 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_tag_tag_text'),
        ('recommend', '0005_auto_20210903_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='accounts.tag'),
        ),
    ]
