# Generated by Django 3.2.4 on 2021-08-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0005_product_review_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review_preference',
        ),
    ]
