# Generated by Django 3.2.4 on 2021-09-03 13:18

from django.db import migrations, models
import django.db.models.deletion
import recommend.utils


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0006_option_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTextCloud',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cloud_image', models.ImageField(upload_to=recommend.utils.user_directory_path)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('prod_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_clouds', to='recommend.product')),
            ],
            options={
                'ordering': ['-created_at', 'prod_no', 'id'],
            },
        ),
    ]
