# Generated by Django 3.2.4 on 2021-08-25 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0007_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_rate',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
