# Generated by Django 3.2.4 on 2021-09-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0007_producttextcloud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttextcloud',
            options={'ordering': ['id', '-created_at']},
        ),
        migrations.AddField(
            model_name='producttextcloud',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
