# Generated by Django 3.2.4 on 2021-08-27 09:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommend', '0008_alter_estimate_estimate_rate'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estimate',
            unique_together={('user', 'prod')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('fav_user', 'fav_prod')},
        ),
    ]
