# Generated by Django 3.2.4 on 2021-08-28 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_birth'),
        ('recommend', '0009_auto_20210827_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.tag')),
            ],
            options={
                'ordering': ['title', 'option_id'],
                'unique_together': {('title', 'tag')},
            },
        ),
    ]
