# Generated by Django 3.2.4 on 2021-09-03 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0009_producttextcloud_user_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='producttextcloud',
            name='prod_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_text_clouds', to='recommend.product'),
        ),
    ]
