# Generated by Django 3.2.4 on 2021-09-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0011_alter_option_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='classification',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.CharField(default='', max_length=5),
        ),
    ]
