# Generated by Django 3.2.4 on 2021-09-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0012_auto_20210908_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
