# Generated by Django 3.1.7 on 2021-06-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('i', 'individual'), ('b', 'business'), ('a', 'ADMIN')], max_length=1, verbose_name='user type'),
        ),
    ]
