# Generated by Django 3.2.4 on 2021-06-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210614_1849'),
    ]

    operations = [
        migrations.RunSQL(
            '''
                INSERT INTO accounts_tag
                (tag_text) VALUES
                ('분류 없음'),
                ('공부'),
                ('게임'),
                ('코딩'),
                ('문서 작업'),
                ('영상 제작'),
                ('디자인'),
                ('학생'),
                ('직장인'),
                ('프리랜서'),
                ('영상 시청'),
                ('웹 서핑')
            '''
        )
    ]
