# Generated by Django 3.1.7 on 2021-06-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210614_0315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nickname',
            options={'ordering': ['part']},
        ),
        migrations.RemoveField(
            model_name='nickname',
            name='adj',
        ),
        migrations.RemoveField(
            model_name='nickname',
            name='noun',
        ),
        migrations.RemoveField(
            model_name='nickname',
            name='number',
        ),
        migrations.AddField(
            model_name='nickname',
            name='content',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='nickname',
            name='emoji',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='nickname',
            name='part',
            field=models.CharField(choices=[('a', '형용사'), ('n', '명사')], default='a', max_length=1, verbose_name='품사'),
        ),
    ]
