# Generated by Django 3.2.4 on 2021-06-21 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210621_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertag',
            options={'ordering': ['tag__tag_code']},
        ),
        migrations.AlterField(
            model_name='usertag',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.tag'),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
