# Generated by Django 3.2.4 on 2021-09-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='classification',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
