# Generated by Django 3.2.4 on 2021-07-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210621_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.PositiveIntegerField(default=1980),
        ),
    ]
