# Generated by Django 3.1.7 on 2021-06-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210614_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='NicknameArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='emoji',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
